version: "3"

services:
  app:
    build:
      context: ./node
      dockerfile: Dockerfile
    image: julioolv/desafio-fullcycle-app
    container_name: app
    tty: true
    entrypoint: wait-for mysql:3306 -t 40 -- ./start.sh
    volumes:
      - ./:/usr/src/app
    networks:
      - nodenet
    depends_on:
      - mysql

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    image: julioolv/desafio-fullcycle-nginx
    container_name: nginx
    tty: true
    networks:
      - nodenet
    ports:
      - 8080:80
    depends_on:
      - app

  mysql:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: mysql
    restart: always
    tty: true
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_ROOT_PASSWORD=123
    volumes:
      - ./mysql:/var/lib/mysql
      - ./dump:/docker-entrypoint-initdb.d
    networks:
      - nodenet

networks:
  nodenet:
    driver: bridge
