FROM node:19 AS build
WORKDIR /usr/src/app
COPY *.json .
RUN npm install --only=prod
COPY . .
RUN npm run build

FROM node:alpine
WORKDIR /app
COPY --from=build /usr/src/app/dist .
CMD [ "node", "index.js" ]